#!/usr/bin/env bash
set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <csv_path>" >&2
    exit 1
fi

CSV="$1"
if [ ! -f "$CSV" ]; then
    echo "Error: CSV not found: $CSV" >&2
    exit 1
fi

TS=$(date +%Y%m%dT%H%M%S)
REPORT_DIR="reports/backtest/${TS}"
mkdir -p "$REPORT_DIR"

MODEL="${2:-monster_v4_2.json}"
BALANCE="${3:-1000}"
ORDER_QTY="${4:-0.001}"
TP_PCT="${5:-0.012}"
SL_PCT="${6:-0.006}"
LOOK_AHEAD="${7:-36}"
COMMISSION="${8:-0.00055}"
INTERVAL="${9:-5}"

for CONF in 0.30 0.45 0.51 0.60; do
  TAG=$(echo "$CONF" | sed 's/0\.//;s/\.//')
  OUT="$REPORT_DIR/backtest_conf_0${TAG}.txt"

  python3 scripts/backtest.py \
    --data-path "$CSV" \
    --model-path "$MODEL" \
    --initial-balance "$BALANCE" \
    --order-qty "$ORDER_QTY" \
    --confidence "$CONF" \
    --tp-pct "$TP_PCT" \
    --sl-pct "$SL_PCT" \
    --look-ahead "$LOOK_AHEAD" \
    --commission "$COMMISSION" \
    --interval-minutes "$INTERVAL" \
    2>&1 | tee "$OUT"
done

# Compute checksums
CSV_SHA=$(sha256sum "$CSV" | awk '{print $1}')
MODEL_SHA=$(sha256sum "$MODEL" | awk '{print $1}')
GIT_SHA=$(git rev-parse HEAD)

# Write manifest
cat > "$REPORT_DIR/manifest.json" <<EOF
{
  "git_sha": "$GIT_SHA",
  "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "data_path": "$CSV",
  "model_path": "$MODEL",
  "source": "binance",
  "symbol": "BTCUSDT",
  "interval": "5m",
  "range": "2024-01-01_to_2024-06-30",
  "confidence_values": [0.30, 0.45, 0.51, 0.60],
  "initial_balance": $BALANCE,
  "order_qty": $ORDER_QTY,
  "tp_pct": $TP_PCT,
  "sl_pct": $SL_PCT,
  "look_ahead": $LOOK_AHEAD,
  "commission": $COMMISSION,
  "interval_minutes": $INTERVAL,
  "csv_sha256": "$CSV_SHA",
  "model_sha256": "$MODEL_SHA"
}
EOF

cat > "$REPORT_DIR/README.md" <<'READMEEOF'
# Sentinel Backtest Report

Reports generated by `scripts/run_backtest_matrix.sh`.

## Files

- `backtest_conf_030.txt` - confidence=0.30
- `backtest_conf_045.txt` - confidence=0.45
- `backtest_conf_051.txt` - confidence=0.51 (production default)
- `backtest_conf_060.txt` - confidence=0.60
- `manifest.json` - metadata: git SHA, model SHA, data SHA, params

## How to read

Each report shows:
- Total trades (long/short)
- Win Rate (%)
- Profit Factor
- Total PnL and final balance
- Max Drawdown
- TP / SL / Timeout counts
- Sharpe (proxy)

## Verdict

See `docs/backtest-handoff-dima.md` for interpretation and next steps.
READMEEOF

echo ""
echo "Reports saved to: $REPORT_DIR"
echo "Manifest: $REPORT_DIR/manifest.json"
ls -lh "$REPORT_DIR/"
